/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/DSHOP": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.DSHOP.id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["DSHOP"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** DSHOP */
          DSHOP?: definitions["DSHOP"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.DSHOP.id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.DSHOP.id"];
        };
        body: {
          /** DSHOP */
          DSHOP?: definitions["DSHOP"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/_products": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter._products.id"];
          name?: parameters["rowFilter._products.name"];
          image?: parameters["rowFilter._products.image"];
          price?: parameters["rowFilter._products.price"];
          description?: parameters["rowFilter._products.description"];
          inserted_at?: parameters["rowFilter._products.inserted_at"];
          updated_at?: parameters["rowFilter._products.updated_at"];
          available?: parameters["rowFilter._products.available"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["_products"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** _products */
          _products?: definitions["_products"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter._products.id"];
          name?: parameters["rowFilter._products.name"];
          image?: parameters["rowFilter._products.image"];
          price?: parameters["rowFilter._products.price"];
          description?: parameters["rowFilter._products.description"];
          inserted_at?: parameters["rowFilter._products.inserted_at"];
          updated_at?: parameters["rowFilter._products.updated_at"];
          available?: parameters["rowFilter._products.available"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter._products.id"];
          name?: parameters["rowFilter._products.name"];
          image?: parameters["rowFilter._products.image"];
          price?: parameters["rowFilter._products.price"];
          description?: parameters["rowFilter._products.description"];
          inserted_at?: parameters["rowFilter._products.inserted_at"];
          updated_at?: parameters["rowFilter._products.updated_at"];
          available?: parameters["rowFilter._products.available"];
        };
        body: {
          /** _products */
          _products?: definitions["_products"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/ds_products": {
    get: {
      parameters: {
        query: {
          inserted_at?: parameters["rowFilter.ds_products.inserted_at"];
          updated_at?: parameters["rowFilter.ds_products.updated_at"];
          name?: parameters["rowFilter.ds_products.name"];
          description?: parameters["rowFilter.ds_products.description"];
          price?: parameters["rowFilter.ds_products.price"];
          image?: parameters["rowFilter.ds_products.image"];
          id?: parameters["rowFilter.ds_products.id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["ds_products"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** ds_products */
          ds_products?: definitions["ds_products"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          inserted_at?: parameters["rowFilter.ds_products.inserted_at"];
          updated_at?: parameters["rowFilter.ds_products.updated_at"];
          name?: parameters["rowFilter.ds_products.name"];
          description?: parameters["rowFilter.ds_products.description"];
          price?: parameters["rowFilter.ds_products.price"];
          image?: parameters["rowFilter.ds_products.image"];
          id?: parameters["rowFilter.ds_products.id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          inserted_at?: parameters["rowFilter.ds_products.inserted_at"];
          updated_at?: parameters["rowFilter.ds_products.updated_at"];
          name?: parameters["rowFilter.ds_products.name"];
          description?: parameters["rowFilter.ds_products.description"];
          price?: parameters["rowFilter.ds_products.price"];
          image?: parameters["rowFilter.ds_products.image"];
          id?: parameters["rowFilter.ds_products.id"];
        };
        body: {
          /** ds_products */
          ds_products?: definitions["ds_products"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/products": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["products"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** products */
          products?: definitions["products"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.products.id"];
        };
        body: {
          /** products */
          products?: definitions["products"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/table_name": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.table_name.id"];
          inserted_at?: parameters["rowFilter.table_name.inserted_at"];
          updated_at?: parameters["rowFilter.table_name.updated_at"];
          data?: parameters["rowFilter.table_name.data"];
          name?: parameters["rowFilter.table_name.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["table_name"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** table_name */
          table_name?: definitions["table_name"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.table_name.id"];
          inserted_at?: parameters["rowFilter.table_name.inserted_at"];
          updated_at?: parameters["rowFilter.table_name.updated_at"];
          data?: parameters["rowFilter.table_name.data"];
          name?: parameters["rowFilter.table_name.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.table_name.id"];
          inserted_at?: parameters["rowFilter.table_name.inserted_at"];
          updated_at?: parameters["rowFilter.table_name.updated_at"];
          data?: parameters["rowFilter.table_name.data"];
          name?: parameters["rowFilter.table_name.name"];
        };
        body: {
          /** table_name */
          table_name?: definitions["table_name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/xxx": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.xxx.id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["xxx"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** xxx */
          xxx?: definitions["xxx"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.xxx.id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.xxx.id"];
        };
        body: {
          /** xxx */
          xxx?: definitions["xxx"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  DSHOP: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
  };
  _products: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    name: string;
    image: string;
    price: number;
    description?: string;
    inserted_at: string;
    updated_at: string;
    available: number;
  };
  ds_products: {
    inserted_at: string;
    updated_at: string;
    name: string;
    description?: string;
    price: number;
    image: string;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
  };
  products: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
  };
  table_name: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    inserted_at: string;
    updated_at: string;
    data?: string;
    name?: string;
  };
  xxx: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** DSHOP */
  "body.DSHOP": definitions["DSHOP"];
  "rowFilter.DSHOP.id": string;
  /** _products */
  "body._products": definitions["_products"];
  "rowFilter._products.id": string;
  "rowFilter._products.name": string;
  "rowFilter._products.image": string;
  "rowFilter._products.price": string;
  "rowFilter._products.description": string;
  "rowFilter._products.inserted_at": string;
  "rowFilter._products.updated_at": string;
  "rowFilter._products.available": string;
  /** ds_products */
  "body.ds_products": definitions["ds_products"];
  "rowFilter.ds_products.inserted_at": string;
  "rowFilter.ds_products.updated_at": string;
  "rowFilter.ds_products.name": string;
  "rowFilter.ds_products.description": string;
  "rowFilter.ds_products.price": string;
  "rowFilter.ds_products.image": string;
  "rowFilter.ds_products.id": string;
  /** products */
  "body.products": definitions["products"];
  "rowFilter.products.id": string;
  /** table_name */
  "body.table_name": definitions["table_name"];
  "rowFilter.table_name.id": string;
  "rowFilter.table_name.inserted_at": string;
  "rowFilter.table_name.updated_at": string;
  "rowFilter.table_name.data": string;
  "rowFilter.table_name.name": string;
  /** xxx */
  "body.xxx": definitions["xxx"];
  "rowFilter.xxx.id": string;
}

export interface operations {}
